### ISSUE TITLE
CommandBus name does not follow Go conventions

### ISSUE THREAD

**Issue by raykrueger** [dadamssg/CommandBus#1]
I'm certain I won't be the only one to bring this up :)

```
import "github.com/dadamssg/CommandBus"
bus := CommandBus.New
```

The upper case letters in the CommandBus name don't follow go conventions.
https://golang.org/doc/effective_go.html#package-names

I'd suggest renaming it to dadamssg/commandbus

```
import "github.com/dadamssg/commandbus"
bus := commandbus.New
```

**Comment by dadamssg** [comment]
thanks @raykrueger! I referenced this [EventBus package](https://github.com/asaskevich/EventBus) when writing it. I thought it looked weird though seeing as how it was the only package i've seen do that. I'll change it :)
